spring:
  client:
    ipAddress: http://192.168.80.210:9901
  datasource:
    url: jdbc:postgresql://192.168.80.210:54321/scp_jszhd
    username: jszhd
    password: jszhd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      max-active: 49
      test-while-idle: true
      time-between-eviction-runs-millis: 599999
      validation-query: SELECT 1
      filters: config,wall,stat
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 9
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: admin

logging:
  path: ../logs/${spring.application.name}