FROM openjdk:8-jdk-alpine
RUN echo "Asia/Shanghai" > /etc/timezone
VOLUME /tmp
ADD scp-purchase-server.jar app.jar
# -Djava.security.egd=file:/dev/./urandom 可解决tomcat可能启动慢的问题
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
EXPOSE 8803